import {
  lucideBlocks,
  lucideBot,
  lucideBoxes,
  lucideCoffee,
  lucideDatabase,
  lucideFileSearch,
  lucideFlaskConical,
  lucideInfinity,
  lucidePanelsTopLeft,
  lucideRadioTower,
  lucideServer,
  lucideSmartphone,
  lucideSparkles,
  lucideSquareCode,
  lucideWrench,
} from '@ng-icons/lucide';
import {
  simpleAngular,
  simpleCss,
  simpleDart,
  simpleDocker,
  simpleDotnet,
  simpleFlutter,
  simpleGit,
  simpleGo,
  simpleJavascript,
  simpleNestjs,
  simpleNextdotjs,
  simpleNodedotjs,
  simplePhp,
  simplePython,
  simpleQwik,
  simpleReact,
  simpleSolid,
  simpleSpring,
  simpleTypescript,
  simpleVuedotjs,
} from '@ng-icons/simple-icons';
import { TechBadge } from '../models/landing-models';

// Every icon a badge below can name. Java and VS Code have no logo in the set, so they borrow one
export const TECH_ICONS = {
  simpleAngular,
  simpleCss,
  simpleDart,
  simpleDocker,
  simpleDotnet,
  simpleFlutter,
  simpleGit,
  simpleGo,
  simpleJavascript,
  simpleNestjs,
  simpleNextdotjs,
  simpleNodedotjs,
  simplePhp,
  simplePython,
  simpleQwik,
  simpleReact,
  simpleSolid,
  simpleSpring,
  simpleTypescript,
  simpleVuedotjs,
  lucideBlocks,
  lucideBot,
  lucideBoxes,
  lucideCoffee,
  lucideDatabase,
  lucideFileSearch,
  lucideFlaskConical,
  lucideInfinity,
  lucidePanelsTopLeft,
  lucideRadioTower,
  lucideServer,
  lucideSmartphone,
  lucideSparkles,
  lucideSquareCode,
  lucideWrench,
};

// Fields have no brand of their own, so they light up in the page's accent
const ACCENT = 'var(--highlight)';

// Languages and frameworks, in the order the marquee shows them. The colours are each brand's
// own: data about the technology rather than the app's palette, lifted where too dark to read
export const TECHNOLOGY_BADGES: readonly TechBadge[] = [
  { tag: 'angular', label: 'Angular', icon: 'simpleAngular', color: '#ff3d6e' },
  { tag: 'react', label: 'React', icon: 'simpleReact', color: '#61dafb' },
  { tag: 'vue', label: 'Vue', icon: 'simpleVuedotjs', color: '#42b883' },
  { tag: 'nextjs', label: 'Next.js', icon: 'simpleNextdotjs', color: '#ffffff' },
  { tag: 'nestjs', label: 'NestJS', icon: 'simpleNestjs', color: '#e0234e' },
  { tag: 'node', label: 'Node.js', icon: 'simpleNodedotjs', color: '#6cc24a' },
  { tag: 'typescript', label: 'TypeScript', icon: 'simpleTypescript', color: '#4a9ae8' },
  { tag: 'javascript', label: 'JavaScript', icon: 'simpleJavascript', color: '#f7df1e' },
  { tag: 'python', label: 'Python', icon: 'simplePython', color: '#4b8bbe' },
  { tag: 'java', label: 'Java', icon: 'lucideCoffee', color: '#f89820' },
  { tag: 'spring', label: 'Spring', icon: 'simpleSpring', color: '#6db33f' },
  { tag: 'golang', label: 'Go', icon: 'simpleGo', color: '#00add8' },
  { tag: 'dotnet', label: '.NET', icon: 'simpleDotnet', color: '#8b6cf6' },
  { tag: 'php', label: 'PHP', icon: 'simplePhp', color: '#8892bf' },
  { tag: 'dart', label: 'Dart', icon: 'simpleDart', color: '#29b6f6' },
  { tag: 'flutter', label: 'Flutter', icon: 'simpleFlutter', color: '#54c5f8' },
  { tag: 'react-native', label: 'React Native', icon: 'simpleReact', color: '#61dafb' },
  { tag: 'qwik', label: 'Qwik', icon: 'simpleQwik', color: '#ac7ef4' },
  { tag: 'solidjs', label: 'SolidJS', icon: 'simpleSolid', color: '#76b3e1' },
  { tag: 'css', label: 'CSS', icon: 'simpleCss', color: '#9b6bdf' },
];

// Fields and tools, for the row that slides the other way. Docker and Git keep their colours
export const FIELD_BADGES: readonly TechBadge[] = [
  { tag: 'backend', label: 'Backend', icon: 'lucideServer', color: ACCENT },
  { tag: 'frontend', label: 'Frontend', icon: 'lucidePanelsTopLeft', color: ACCENT },
  { tag: 'mobile', label: 'Móvil', icon: 'lucideSmartphone', color: ACCENT },
  { tag: 'devops', label: 'DevOps', icon: 'lucideInfinity', color: ACCENT },
  { tag: 'docker', label: 'Docker', icon: 'simpleDocker', color: '#2496ed' },
  { tag: 'database', label: 'Bases de datos', icon: 'lucideDatabase', color: ACCENT },
  { tag: 'architecture', label: 'Arquitectura', icon: 'lucideBlocks', color: ACCENT },
  { tag: 'microservices', label: 'Microservicios', icon: 'lucideBoxes', color: ACCENT },
  { tag: 'realtime', label: 'Tiempo real', icon: 'lucideRadioTower', color: ACCENT },
  { tag: 'testing', label: 'Testing', icon: 'lucideFlaskConical', color: ACCENT },
  { tag: 'git', label: 'Git', icon: 'simpleGit', color: '#f05032' },
  { tag: 'vscode', label: 'VS Code', icon: 'lucideSquareCode', color: '#3ea6ff' },
  { tag: 'tools', label: 'Herramientas', icon: 'lucideWrench', color: ACCENT },
  { tag: 'ai', label: 'Inteligencia artificial', icon: 'lucideSparkles', color: ACCENT },
  { tag: 'agents', label: 'Agentes de IA', icon: 'lucideBot', color: ACCENT },
  { tag: 'rag', label: 'RAG', icon: 'lucideFileSearch', color: ACCENT },
];
